Batch mode
awslabs/amazon-omics-tools pull request #69
Opened 2024-09-27 21:45 UTC by markjschreiber

*Description of changes:*
Adds a "batch" mode to allow generation of an aggregate report over multiple runs and scattered tasks.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-01 22:09 UTC, KevinSayers requested changes
We should clean up the noted redundant code, but otherwise looks good.

2024-10-01 22:09 UTC, KevinSayers commented on tests/run_analyzer/unit/test_writeconfig.py
Can remove this once we switch to `utils` instead of `writeconfig.get_base_task`

2024-10-01 22:09 UTC, KevinSayers commented on omics/cli/run_analyzer/batch.py
> +    "maximumCpuUtilizationRatio",
Adding mean CPU/Mem/GPU would be beneficial.

2024-10-02 14:17 UTC, markjschreiber commented on omics/cli/run_analyzer/__main__.py
> +from . import utils, writeconfig
Good idea!

2024-10-02 14:17 UTC, markjschreiber commented on tests/run_analyzer/unit/test_writeconfig.py
Done

2024-10-02 15:20 UTC, KevinSayers approved these changes
Looks good!

2024-10-02 15:34 UTC, merged